---@meta _

--[[
---- general
--]]

--- Input checking functions all return one of the press status constants depending on the state of the checked input.
---
---@alias PressStatus
---| `input.NEUTRAL`
---| `input.RELEASED`
---| `input.HELD`
---| `input.PRESSED`



--[[
---- Controls
--]]

--- Valid control names for `input.checkControl()` and `PlayerInstance:control()`.
---
---@alias PlayerControl
---| 'left'
---| 'right'
---| 'up'
---| 'down'
---| 'jump'
---|
---| 'ability1'
---| 'ability2'
---| 'ability3'
---| 'ability4'
---|
---| 'use'
---| 'enter'
---| 'swap'




--[[
---- keyboard
--]]

--- Valid keys for `input.checkKeyboard()`.
---
---@alias KeyboardKey
---|-- Special
---| 'nokey' TODO
---| 'anykey' Used to check if any key is pressed/held/released
---|
---|-- Modifiers
---| 'shift'
---| 'control'
---| 'alt'
---|
---|-- Text
---| 'space'
---| 'a'
---| 'b'
---| 'c'
---| 'd'
---| 'e'
---| 'f'
---| 'g'
---| 'h'
---| 'i'
---| 'j'
---| 'k'
---| 'l'
---| 'm'
---| 'n'
---| 'o'
---| 'p'
---| 'q'
---| 'r'
---| 's'
---| 't'
---| 'u'
---| 'v'
---| 'w'
---| 'x'
---| 'y'
---| 'z'
---| 'A'
---| 'B'
---| 'C'
---| 'D'
---| 'E'
---| 'F'
---| 'G'
---| 'H'
---| 'I'
---| 'J'
---| 'K'
---| 'L'
---| 'M'
---| 'N'
---| 'O'
---| 'P'
---| 'Q'
---| 'R'
---| 'S'
---| 'T'
---| 'U'
---| 'V'
---| 'W'
---| 'X'
---| 'Y'
---| 'Z'
---|
---|-- Numbers
---| '0'
---| '1'
---| '2'
---| '3'
---| '4'
---| '5'
---| '6'
---| '7'
---| '8'
---| '9'
---|
---|-- Numpad
---| 'numpad0'
---| 'numpad1'
---| 'numpad2'
---| 'numpad3'
---| 'numpad4'
---| 'numpad5'
---| 'numpad6'
---| 'numpad7'
---| 'numpad8'
---| 'numpad9'
---|
---|-- Math
---| 'decimal'
---| 'multiply'
---| 'divide'
---| 'add'
---| 'subtract'
---|
---|-- Function Keys
---| 'f1'
---| 'f2'
---| 'f3'
---| 'f4'
---| 'f5'
---| 'f6'
---| 'f7'
---| 'f8'
---| 'f9'
---| 'f10'
---| 'f11'
---| 'f12'
---|
---|-- Arrow Keys
---| 'left'
---| 'right'
---| 'up'
---| 'down'
---|
---|-- Action Keys
---| 'enter'
---| 'escape'
---| 'home'
---| 'end'
---| 'delete'
---| 'insert'
---| 'pageup'
---| 'pagedown'
---| 'pause'
---| 'printscreen'
---| 'tab'
---| 'backspace'



--[[
---- controller
--]]

---@alias GamepadId number

--- Valid buttons for `input.checkGamepad()`.
---
---@alias GamepadButton
---| 'face1' Face button 1 (A or Cross)
---| 'face2' Face button 2, (B or Circle)
---| 'face3' Face button 3 (X or Square)
---| 'face4' Face button 4 (Y or Triangle)
---| 'shoulderl' Left Shoulder Button (Left Bumper or L1)
---| 'shoulderlb' Left Shoulder Trigger (Left Trigger or L2)
---| 'shoulderr' Right Shoulder Button (Right Bumper or R1)
---| 'shoulderrb' Right Shoulder Trigger (Right Trigger or R2)
---| 'select' The select button (Touch-Pad press on a PS4 controller)
---| 'start' The start button (“Options” button on a PS4 controller)
---| 'stickl' The left stick pressed (as a button)
---| 'stickr' The right stick pressed (as a button)
---| 'padu' Up on the D-pad
---| 'padd' Down on the D-pad
---| 'padl' Left on the D-pad
---| 'padr' Right on the D-pad

--- Valid axises for `input.getGamepadAxis()`.
---
---@alias GamepadAxis
---| 'lh' Left stick horizontal
---| 'lv' Left stick vertical
---| 'rh' Right stick horizontal
---| 'rv' Right stick vertical



--[[
---- mouse functions
--]]

--- Valid buttons for `input.checkMouse()`.
---
---@alias MouseButton
---| 'none'
---| 'left'
---| 'right'
---| 'middle'

--- Return values of `input.getMouseScroll()`.
---
---@alias ScrollState
---| `0`  no scroll
---| `-1` up scroll
---| `1`  down scroll
